variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: 'Friday'
  BUILD_OUTPUT_PATH: 'Friday/bin/Release/net6.0/'
  GIT_SUBMODULE_STRATEGY: recursive

# ### Define global cache rule
#
# Before building the project, all dependencies (e.g. third-party NuGet packages)
# must be restored. Jobs on GitLab.com's Shared Runners are executed on autoscaled machines.
cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/project.assets.json'
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/*.csproj.nuget.*'
    - '$BUILD_OUTPUT_PATH'
  policy: pull-push

stages:
  - publish

publish:image:
  image: docker:latest
  stage: publish
  only:
    - master

  tags: ["build", "docker"]
  
  services:
    - docker:dind
  
  before_script:
    - echo "$HARBOR_PASS" | docker login -u "$HARBOR_USER" "$HARBOR_URL" --password-stdin
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" .
    - docker tag $CI_REGISTRY_IMAGE:latest $HARBOR_HOST/$HARBOR_PROJECT/$CI_REGISTRY_IMAGE:latest
    - docker push "$HARBOR_HOST/$HARBOR_PROJECT/$CI_REGISTRY_IMAGE:latest"
